// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package SerializeDemo.ProtoBufDemo.ProtoBuf;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string gender = 2;</code>
     */
    String getGender();
    /**
     * <code>optional string gender = 2;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>optional .Address addr = 4;</code>
     */
    boolean hasAddr();
    /**
     * <code>optional .Address addr = 4;</code>
     */
    SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getAddr();
    /**
     * <code>optional .Address addr = 4;</code>
     */
    SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder getAddrOrBuilder();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      gender_ = "";
      age_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder subBuilder = null;
              if (addr_ != null) {
                subBuilder = addr_.toBuilder();
              }
              addr_ = input.readMessage(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(addr_);
                addr_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.class, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 2;
    private volatile Object gender_;
    /**
     * <code>optional string gender = 2;</code>
     */
    public String getGender() {
      Object ref = gender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDR_FIELD_NUMBER = 4;
    private SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address addr_;
    /**
     * <code>optional .Address addr = 4;</code>
     */
    public boolean hasAddr() {
      return addr_ != null;
    }
    /**
     * <code>optional .Address addr = 4;</code>
     */
    public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getAddr() {
      return addr_ == null ? SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.getDefaultInstance() : addr_;
    }
    /**
     * <code>optional .Address addr = 4;</code>
     */
    public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder getAddrOrBuilder() {
      return getAddr();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gender_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (addr_ != null) {
        output.writeMessage(4, getAddr());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gender_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (addr_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAddr());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User)) {
        return super.equals(obj);
      }
      SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User other = (SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getGender()
          .equals(other.getGender());
      result = result && (getAge()
          == other.getAge());
      result = result && (hasAddr() == other.hasAddr());
      if (hasAddr()) {
        result = result && getAddr()
            .equals(other.getAddr());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasAddr()) {
        hash = (37 * hash) + ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getAddr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.class, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.Builder.class);
      }

      // Construct using SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        gender_ = "";

        age_ = 0;

        if (addrBuilder_ == null) {
          addr_ = null;
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_User_descriptor;
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User getDefaultInstanceForType() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.getDefaultInstance();
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User build() {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User buildPartial() {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User result = new SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User(this);
        result.name_ = name_;
        result.gender_ = gender_;
        result.age_ = age_;
        if (addrBuilder_ == null) {
          result.addr_ = addr_;
        } else {
          result.addr_ = addrBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User) {
          return mergeFrom((SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User other) {
        if (other == SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasAddr()) {
          mergeAddr(other.getAddr());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object gender_ = "";
      /**
       * <code>optional string gender = 2;</code>
       */
      public String getGender() {
        Object ref = gender_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string gender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gender = 2;</code>
       */
      public Builder setGender(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 2;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 2;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address addr_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder> addrBuilder_;
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public boolean hasAddr() {
        return addrBuilder_ != null || addr_ != null;
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getAddr() {
        if (addrBuilder_ == null) {
          return addr_ == null ? SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.getDefaultInstance() : addr_;
        } else {
          return addrBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public Builder setAddr(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addr_ = value;
          onChanged();
        } else {
          addrBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public Builder setAddr(
          SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder builderForValue) {
        if (addrBuilder_ == null) {
          addr_ = builderForValue.build();
          onChanged();
        } else {
          addrBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public Builder mergeAddr(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address value) {
        if (addrBuilder_ == null) {
          if (addr_ != null) {
            addr_ =
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.newBuilder(addr_).mergeFrom(value).buildPartial();
          } else {
            addr_ = value;
          }
          onChanged();
        } else {
          addrBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public Builder clearAddr() {
        if (addrBuilder_ == null) {
          addr_ = null;
          onChanged();
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder getAddrBuilder() {
        
        onChanged();
        return getAddrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder getAddrOrBuilder() {
        if (addrBuilder_ != null) {
          return addrBuilder_.getMessageOrBuilder();
        } else {
          return addr_ == null ?
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.getDefaultInstance() : addr_;
        }
      }
      /**
       * <code>optional .Address addr = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder> 
          getAddrFieldBuilder() {
        if (addrBuilder_ == null) {
          addrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder>(
                  getAddr(),
                  getParentForChildren(),
                  isClean());
          addr_ = null;
        }
        return addrBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User();
    }

    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string country = 1;</code>
     */
    String getCountry();
    /**
     * <code>optional string country = 1;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional string city = 2;</code>
     */
    String getCity();
    /**
     * <code>optional string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      country_ = "";
      city_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.class, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder.class);
    }

    public static final int COUNTRY_FIELD_NUMBER = 1;
    private volatile Object country_;
    /**
     * <code>optional string country = 1;</code>
     */
    public String getCountry() {
      Object ref = country_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>optional string country = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile Object city_;
    /**
     * <code>optional string city = 2;</code>
     */
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, country_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, country_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address)) {
        return super.equals(obj);
      }
      SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address other = (SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address) obj;

      boolean result = true;
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getCity()
          .equals(other.getCity());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.class, SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.Builder.class);
      }

      // Construct using SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        country_ = "";

        city_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.internal_static_Address_descriptor;
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getDefaultInstanceForType() {
        return SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.getDefaultInstance();
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address build() {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address buildPartial() {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address result = new SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address(this);
        result.country_ = country_;
        result.city_ = city_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address) {
          return mergeFrom((SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address other) {
        if (other == SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address.getDefaultInstance()) return this;
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object country_ = "";
      /**
       * <code>optional string country = 1;</code>
       */
      public String getCountry() {
        Object ref = country_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string country = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 1;</code>
       */
      public Builder setCountry(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 1;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 1;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private Object city_ = "";
      /**
       * <code>optional string city = 2;</code>
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address();
    }

    public static SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public SerializeDemo.ProtoBufDemo.ProtoBuf.UserProto.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nUser.proto\"I\n\004User\022\014\n\004name\030\001 \001(\t\022\016\n\006ge" +
      "nder\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\026\n\004addr\030\004 \001(\0132\010." +
      "Address\"(\n\007Address\022\017\n\007country\030\001 \001(\t\022\014\n\004c" +
      "ity\030\002 \001(\tB\025\n\010java.comB\tUserProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new String[] { "Name", "Gender", "Age", "Addr", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new String[] { "Country", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
